package modelo;
// Generated 7 ene. 2021 20:38:51 by Hibernate Tools 5.4.21.Final

/**
 * Entornosmuni generated by hbm2java
 */
public class Entornosmuni implements java.io.Serializable {

	private EntornosmuniId id;
	private Entornos entornos;
	private Municipios municipios;

	public Entornosmuni() {
	}

	public Entornosmuni(EntornosmuniId id, Entornos entornos, Municipios municipios) {
		this.id = id;
		this.entornos = entornos;
		this.municipios = municipios;
	}

	public EntornosmuniId getId() {
		return this.id;
	}

	public void setId(EntornosmuniId id) {
		this.id = id;
	}

	public Entornos getEntornos() {
		return this.entornos;
	}

	public void setEntornos(Entornos entornos) {
		this.entornos = entornos;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

}
