package modelo;
// Generated Jan 3, 2021, 9:45:27 PM by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Informes generated by hbm2java
 */
@SuppressWarnings("serial")
public class Informes implements java.io.Serializable {

	private Integer id;
	private Estaciones estaciones;
	private String formato;
	private String nombre;
	private String url;
	@SuppressWarnings("rawtypes")
	private Set horarios = new HashSet(0);

	public Informes() {
	}

	public Informes(Estaciones estaciones, String url) {
		this.estaciones = estaciones;
		this.url = url;
	}

	public Informes(Estaciones estaciones, String formato, String url, @SuppressWarnings("rawtypes") Set horarios) {
		this.estaciones = estaciones;
		this.formato = formato;
		this.url = url;
		this.horarios = horarios;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public String getFormato() {
		return this.formato;
	}

	public void setFormato(String formato) {
		this.formato = formato;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	
	@SuppressWarnings("rawtypes")
	public Set getHorarios() {
		return this.horarios;
	}

	public void setHorarios(@SuppressWarnings("rawtypes") Set horarios) {
		this.horarios = horarios;
	}

	@Override
	public String toString() {
		return "Informes [id=" + id + ", estaciones=" + estaciones + ", formato=" + formato + ", nombre=" + nombre
				+ ", url=" + url + ", horarios=" + horarios + "]";
	}
	
}
