package modelo;
// Generated 1 feb. 2021 20:13:50 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Informes generated by hbm2java
 */
public class Informes implements java.io.Serializable {

	private Integer id;
	private Estaciones estaciones;
	private String formato;
	private String url;
	private String hash;
	private String nombre;
	private Set horarios = new HashSet(0);

	public Informes() {
	}

	public Informes(Estaciones estaciones, String url, String hash) {
		this.estaciones = estaciones;
		this.url = url;
		this.hash = hash;
	}

	public Informes(Estaciones estaciones, String formato, String url, String hash, Set horarios) {
		this.estaciones = estaciones;
		this.formato = formato;
		this.url = url;
		this.hash = hash;
		this.horarios = horarios;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public String getFormato() {
		return this.formato;
	}

	public void setFormato(String formato) {
		this.formato = formato;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	public Set getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set horarios) {
		this.horarios = horarios;
	}

}
