package modelo;
// Generated 19 ene. 2021 17:44:31 by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Provincias generated by hbm2java
 */
public class Provincias implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set municipioses = new HashSet(0);
	private Set estacioneses = new HashSet(0);

	public Provincias() {
	}

	public Provincias(String nombre) {
		this.nombre = nombre;
	}

	public Provincias(String nombre, Set municipioses, Set estacioneses) {
		this.nombre = nombre;
		this.municipioses = municipioses;
		this.estacioneses = estacioneses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getMunicipioses() {
		return this.municipioses;
	}

	public void setMunicipioses(Set municipioses) {
		this.municipioses = municipioses;
	}

	public Set getEstacioneses() {
		return this.estacioneses;
	}

	public void setEstacioneses(Set estacioneses) {
		this.estacioneses = estacioneses;
	}

}
