package modelo;
// Generated 14 ene. 2021 17:29:18 by Hibernate Tools 5.4.21.Final

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer id;
	private String usuario;
	private String contrasena;
	private String pregunta;
	private String respuesta;

	public Usuario() {
	}

	public Usuario(String usuario, String contrasena, String pregunta, String respuesta) {
		this.usuario = usuario;
		this.contrasena = contrasena;
		this.pregunta = pregunta;
		this.respuesta = respuesta;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public String getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(String pregunta) {
		this.pregunta = pregunta;
	}

	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

}
