package modelo;
// Generated Jan 21, 2021, 3:55:47 AM by Hibernate Tools 5.4.18.Final

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String contrasena;
	private String pregunta;
	private String respuesta;

	public Usuario() {
	}

	public Usuario(String nombre, String contrasena, String pregunta, String respuesta) {
		this.nombre = nombre;
		this.contrasena = contrasena;
		this.pregunta = pregunta;
		this.respuesta = respuesta;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public String getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(String pregunta) {
		this.pregunta = pregunta;
	}

	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

}
