package modelo;
// Generated 1 feb. 2021 20:13:50 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String contrasena;
	private String pregunta;
	private String respuesta;
	private Set entornosfavoritoses = new HashSet(0);
	private Set municipiosfavoritoses = new HashSet(0);
	private Set fotoses = new HashSet(0);

	public Usuario() {
	}

	public Usuario(String nombre, String contrasena, String pregunta, String respuesta) {
		this.nombre = nombre;
		this.contrasena = contrasena;
		this.pregunta = pregunta;
		this.respuesta = respuesta;
	}

	public Usuario(String nombre, String contrasena, String pregunta, String respuesta, Set entornosfavoritoses,
			Set municipiosfavoritoses, Set fotoses) {
		this.nombre = nombre;
		this.contrasena = contrasena;
		this.pregunta = pregunta;
		this.respuesta = respuesta;
		this.entornosfavoritoses = entornosfavoritoses;
		this.municipiosfavoritoses = municipiosfavoritoses;
		this.fotoses = fotoses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public String getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(String pregunta) {
		this.pregunta = pregunta;
	}

	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	public Set getEntornosfavoritoses() {
		return this.entornosfavoritoses;
	}

	public void setEntornosfavoritoses(Set entornosfavoritoses) {
		this.entornosfavoritoses = entornosfavoritoses;
	}

	public Set getMunicipiosfavoritoses() {
		return this.municipiosfavoritoses;
	}

	public void setMunicipiosfavoritoses(Set municipiosfavoritoses) {
		this.municipiosfavoritoses = municipiosfavoritoses;
	}

	public Set getFotoses() {
		return this.fotoses;
	}

	public void setFotoses(Set fotoses) {
		this.fotoses = fotoses;
	}

}
