package hiberclass;
// Generated 21 dic. 2020 22:57:37 by Hibernate Tools 5.4.21.Final

/**
 * Entornosmuni generated by hbm2java
 */
public class Entornosmuni implements java.io.Serializable {

	private Integer id;
	private Entornos entornos;
	private Municipios municipios;

	public Entornosmuni() {
	}

	public Entornosmuni(Entornos entornos, Municipios municipios) {
		this.entornos = entornos;
		this.municipios = municipios;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Entornos getEntornos() {
		return this.entornos;
	}

	public void setEntornos(Entornos entornos) {
		this.entornos = entornos;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

}
