package hiberclass;
// Generated 22 dic. 2020 17:17:54 by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Municipios generated by hbm2java
 */
public class Municipios implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String descripcion;
	private Double latitud;
	private Double longitud;
	private Integer codigo;
	private Set entornosmunis = new HashSet(0);

	public Municipios() {
	}

	public Municipios(String nombre) {
		this.nombre = nombre;
	}

	public Municipios(String nombre, String descripcion, Double latitud, Double longitud, Integer codigo,
			Set entornosmunis) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.latitud = latitud;
		this.longitud = longitud;
		this.codigo = codigo;
		this.entornosmunis = entornosmunis;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public Set getEntornosmunis() {
		return this.entornosmunis;
	}

	public void setEntornosmunis(Set entornosmunis) {
		this.entornosmunis = entornosmunis;
	}
	
	public boolean isNull()
	{
		if(nombre != null)
			return false;
		if(descripcion != null)
			return false;
		if(latitud != null)
			return false;
		if(longitud != null)
			return false;
		if(codigo != null)
			return false;
		if(entornosmunis != null)
			return false;
		return true;
	}
}
